CREATE TABLE IF NOT EXISTS users (
    user_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 0) PRIMARY KEY,
    login varchar(255),
    name varchar (255),
    email varchar(255),
    birthday date
);

CREATE TABLE IF NOT EXISTS genre (
    genre_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    genre_name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa (
     mpa_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
     mpa_name varchar(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    film_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    name varchar(255) NOT NULL,
    description varchar(200),
    mpa_id int REFERENCES mpa (mpa_id),
    release_date date,
    duration int CONSTRAINT positive_duration CHECK (duration > 0)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id int REFERENCES films (film_id),
    genre_id int REFERENCES genre (genre_id),
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS likes (
    film_id int REFERENCES films (film_id),
    user_id int REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS friends (
    friend_one int REFERENCES users (user_id),
    friend_two int REFERENCES users (user_id)
);



