CREATE TABLE IF NOT EXISTS genre (
    genre_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name varchar(100) NOT NULL
    );

CREATE TABLE IF NOT EXISTS mpa (
    mpa_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name varchar(45) NOT NULL
    );

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    login varchar(255) NOT NULL,
    name varchar (255) NOT NULL,
    email varchar(255) NOT NULL,
    birthday date
);

CREATE TABLE IF NOT EXISTS films (
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    name varchar(255) NOT NULL,
    description varchar(200) NOT NULL,
    mpa_id BIGINT REFERENCES mpa (mpa_id) ON DELETE CASCADE,
    release_date date NOT NULL,
    duration INTEGER
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id BIGINT REFERENCES films (film_id),
    genre_id BIGINT REFERENCES genre (genre_id)
);

CREATE TABLE IF NOT EXISTS likes (
    film_id BIGINT REFERENCES films (film_id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friends (
    friend_one BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    friend_two BIGINT REFERENCES users (user_id) ON DELETE CASCADE
);



